In [28]:
import pandas as pd
import datetime as dt
from decimal import Decimal

In [29]:
df = pd.read_csv('clean_upcoming_df_2022.csv')
df

,movie_id,title,movie_rating,release_date,run_time,genre_name,director,writer,actors,language,meta_score,imdb_rating,box_office,Trash
0,0,The Batman,PG-13,2022-03-04,175,"Action, Crime, Drama",Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",English,0.0,0.0,0.0,min
1,1,A Day to Die,0,1970-01-01,0,Action,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",English,0.0,0.0,0.0,NaN
2,2,He Was Asking for It: A Noir Film,0,2022-04-30,0,"Short, Crime",Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",English,0.0,0.0,0.0,NaN
3,3,Tyson's Run,PG,2022-03-11,103,Drama,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",English,0.0,0.0,0.0,min
4,4,X,R,2022-03-18,0,Horror,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",English,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,2022-12-16,0,"Action, Adventure, Fantasy",James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",English,0.0,0.0,0.0,NaN
79,79,Untitled Illumination Entertainment Project,0,2022-12-21,0,"Animation, Adventure, Comedy","Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",English,0.0,0.0,0.0,NaN
80,80,I Wanna Dance with Somebody,0,2022-12-23,0,"Biography, Music",Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0,0.0,0.0,0.0,NaN
81,81,A Man Called Otto,0,1970-01-01,0,"Comedy, Drama",Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",English,0.0,0.0,0.0,NaN
82,82,Babylon,0,2023-01-06,0,Drama,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",English,0.0,0.0,0.0,NaN

In [30]:
df['language'] = df['language'].fillna('NA')
df

,movie_id,title,movie_rating,release_date,run_time,genre_name,director,writer,actors,language,meta_score,imdb_rating,box_office,Trash
0,0,The Batman,PG-13,2022-03-04,175,"Action, Crime, Drama",Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",English,0.0,0.0,0.0,min
1,1,A Day to Die,0,1970-01-01,0,Action,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",English,0.0,0.0,0.0,NaN
2,2,He Was Asking for It: A Noir Film,0,2022-04-30,0,"Short, Crime",Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",English,0.0,0.0,0.0,NaN
3,3,Tyson's Run,PG,2022-03-11,103,Drama,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",English,0.0,0.0,0.0,min
4,4,X,R,2022-03-18,0,Horror,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",English,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,2022-12-16,0,"Action, Adventure, Fantasy",James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",English,0.0,0.0,0.0,NaN
79,79,Untitled Illumination Entertainment Project,0,2022-12-21,0,"Animation, Adventure, Comedy","Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",English,0.0,0.0,0.0,NaN
80,80,I Wanna Dance with Somebody,0,2022-12-23,0,"Biography, Music",Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0,0.0,0.0,0.0,NaN
81,81,A Man Called Otto,0,1970-01-01,0,"Comedy, Drama",Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",English,0.0,0.0,0.0,NaN
82,82,Babylon,0,2023-01-06,0,Drama,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",English,0.0,0.0,0.0,NaN

In [31]:
df['meta_score'] = df['meta_score'].fillna('0')
df

,movie_id,title,movie_rating,release_date,run_time,genre_name,director,writer,actors,language,meta_score,imdb_rating,box_office,Trash
0,0,The Batman,PG-13,2022-03-04,175,"Action, Crime, Drama",Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",English,0.0,0.0,0.0,min
1,1,A Day to Die,0,1970-01-01,0,Action,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",English,0.0,0.0,0.0,NaN
2,2,He Was Asking for It: A Noir Film,0,2022-04-30,0,"Short, Crime",Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",English,0.0,0.0,0.0,NaN
3,3,Tyson's Run,PG,2022-03-11,103,Drama,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",English,0.0,0.0,0.0,min
4,4,X,R,2022-03-18,0,Horror,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",English,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,2022-12-16,0,"Action, Adventure, Fantasy",James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",English,0.0,0.0,0.0,NaN
79,79,Untitled Illumination Entertainment Project,0,2022-12-21,0,"Animation, Adventure, Comedy","Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",English,0.0,0.0,0.0,NaN
80,80,I Wanna Dance with Somebody,0,2022-12-23,0,"Biography, Music",Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0,0.0,0.0,0.0,NaN
81,81,A Man Called Otto,0,1970-01-01,0,"Comedy, Drama",Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",English,0.0,0.0,0.0,NaN
82,82,Babylon,0,2023-01-06,0,Drama,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",English,0.0,0.0,0.0,NaN

In [32]:
df['release_date'].isnull().sum()

0

In [33]:
df['release_date']=df['release_date'].fillna('1900-01-01')
df

,movie_id,title,movie_rating,release_date,run_time,genre_name,director,writer,actors,language,meta_score,imdb_rating,box_office,Trash
0,0,The Batman,PG-13,2022-03-04,175,"Action, Crime, Drama",Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",English,0.0,0.0,0.0,min
1,1,A Day to Die,0,1970-01-01,0,Action,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",English,0.0,0.0,0.0,NaN
2,2,He Was Asking for It: A Noir Film,0,2022-04-30,0,"Short, Crime",Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",English,0.0,0.0,0.0,NaN
3,3,Tyson's Run,PG,2022-03-11,103,Drama,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",English,0.0,0.0,0.0,min
4,4,X,R,2022-03-18,0,Horror,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",English,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,2022-12-16,0,"Action, Adventure, Fantasy",James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",English,0.0,0.0,0.0,NaN
79,79,Untitled Illumination Entertainment Project,0,2022-12-21,0,"Animation, Adventure, Comedy","Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",English,0.0,0.0,0.0,NaN
80,80,I Wanna Dance with Somebody,0,2022-12-23,0,"Biography, Music",Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0,0.0,0.0,0.0,NaN
81,81,A Man Called Otto,0,1970-01-01,0,"Comedy, Drama",Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",English,0.0,0.0,0.0,NaN
82,82,Babylon,0,2023-01-06,0,Drama,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",English,0.0,0.0,0.0,NaN

In [34]:
df['release_date'].isnull().sum()

0

In [35]:
df['release_date'] = pd.to_datetime(df['release_date']).dt.date
df

,movie_id,title,movie_rating,release_date,run_time,genre_name,director,writer,actors,language,meta_score,imdb_rating,box_office,Trash
0,0,The Batman,PG-13,2022-03-04,175,"Action, Crime, Drama",Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",English,0.0,0.0,0.0,min
1,1,A Day to Die,0,1970-01-01,0,Action,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",English,0.0,0.0,0.0,NaN
2,2,He Was Asking for It: A Noir Film,0,2022-04-30,0,"Short, Crime",Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",English,0.0,0.0,0.0,NaN
3,3,Tyson's Run,PG,2022-03-11,103,Drama,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",English,0.0,0.0,0.0,min
4,4,X,R,2022-03-18,0,Horror,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",English,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,2022-12-16,0,"Action, Adventure, Fantasy",James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",English,0.0,0.0,0.0,NaN
79,79,Untitled Illumination Entertainment Project,0,2022-12-21,0,"Animation, Adventure, Comedy","Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",English,0.0,0.0,0.0,NaN
80,80,I Wanna Dance with Somebody,0,2022-12-23,0,"Biography, Music",Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0,0.0,0.0,0.0,NaN
81,81,A Man Called Otto,0,1970-01-01,0,"Comedy, Drama",Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",English,0.0,0.0,0.0,NaN
82,82,Babylon,0,2023-01-06,0,Drama,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",English,0.0,0.0,0.0,NaN

In [36]:
df['movie_rating']=df['movie_rating'].fillna('NA')
df

,movie_id,title,movie_rating,release_date,run_time,genre_name,director,writer,actors,language,meta_score,imdb_rating,box_office,Trash
0,0,The Batman,PG-13,2022-03-04,175,"Action, Crime, Drama",Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",English,0.0,0.0,0.0,min
1,1,A Day to Die,0,1970-01-01,0,Action,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",English,0.0,0.0,0.0,NaN
2,2,He Was Asking for It: A Noir Film,0,2022-04-30,0,"Short, Crime",Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",English,0.0,0.0,0.0,NaN
3,3,Tyson's Run,PG,2022-03-11,103,Drama,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",English,0.0,0.0,0.0,min
4,4,X,R,2022-03-18,0,Horror,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",English,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,2022-12-16,0,"Action, Adventure, Fantasy",James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",English,0.0,0.0,0.0,NaN
79,79,Untitled Illumination Entertainment Project,0,2022-12-21,0,"Animation, Adventure, Comedy","Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",English,0.0,0.0,0.0,NaN
80,80,I Wanna Dance with Somebody,0,2022-12-23,0,"Biography, Music",Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0,0.0,0.0,0.0,NaN
81,81,A Man Called Otto,0,1970-01-01,0,"Comedy, Drama",Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",English,0.0,0.0,0.0,NaN
82,82,Babylon,0,2023-01-06,0,Drama,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",English,0.0,0.0,0.0,NaN

In [37]:
#create movie table setup
movie = pd.DataFrame(df[['movie_id','title','movie_rating','genre_name','imdb_rating','director',
                        'writer','actors','box_office','run_time','release_date','meta_score']])
movie

,movie_id,title,movie_rating,genre_name,imdb_rating,director,writer,actors,box_office,run_time,release_date,meta_score
0,0,The Batman,PG-13,"Action, Crime, Drama",0.0,Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",0.0,175,2022-03-04,0.0
1,1,A Day to Die,0,Action,0.0,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",0.0,0,1970-01-01,0.0
2,2,He Was Asking for It: A Noir Film,0,"Short, Crime",0.0,Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",0.0,0,2022-04-30,0.0
3,3,Tyson's Run,PG,Drama,0.0,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",0.0,103,2022-03-11,0.0
4,4,X,R,Horror,0.0,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",0.0,0,2022-03-18,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,"Action, Adventure, Fantasy",0.0,James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",0.0,0,2022-12-16,0.0
79,79,Untitled Illumination Entertainment Project,0,"Animation, Adventure, Comedy",0.0,"Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",0.0,0,2022-12-21,0.0
80,80,I Wanna Dance with Somebody,0,"Biography, Music",0.0,Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0.0,0,2022-12-23,0.0
81,81,A Man Called Otto,0,"Comedy, Drama",0.0,Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",0.0,0,1970-01-01,0.0
82,82,Babylon,0,Drama,0.0,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",0.0,0,2023-01-06,0.0

In [38]:
#export to csv
movie.to_csv ('final_movie_list_upcoming.csv', header=True, index=False)
movie

,movie_id,title,movie_rating,genre_name,imdb_rating,director,writer,actors,box_office,run_time,release_date,meta_score
0,0,The Batman,PG-13,"Action, Crime, Drama",0.0,Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan",0.0,175,2022-03-04,0.0
1,1,A Day to Die,0,Action,0.0,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",0.0,0,1970-01-01,0.0
2,2,He Was Asking for It: A Noir Film,0,"Short, Crime",0.0,Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",0.0,0,2022-04-30,0.0
3,3,Tyson's Run,PG,Drama,0.0,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",0.0,103,2022-03-11,0.0
4,4,X,R,Horror,0.0,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow",0.0,0,2022-03-18,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,"Action, Adventure, Fantasy",0.0,James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",0.0,0,2022-12-16,0.0
79,79,Untitled Illumination Entertainment Project,0,"Animation, Adventure, Comedy",0.0,"Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",0.0,0,2022-12-21,0.0
80,80,I Wanna Dance with Somebody,0,"Biography, Music",0.0,Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters",0.0,0,2022-12-23,0.0
81,81,A Man Called Otto,0,"Comedy, Drama",0.0,Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",0.0,0,1970-01-01,0.0
82,82,Babylon,0,Drama,0.0,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",0.0,0,2023-01-06,0.0

In [39]:
#create movie table setup
movie2 = pd.DataFrame(movie[['movie_id','title','movie_rating', 'release_date', 'run_time', 'meta_score', 'imdb_rating','box_office']])

#export to csv
movie2.to_csv ('upcoming_movie.csv', header=True, index=False)

movie2

,movie_id,title,movie_rating,release_date,run_time,meta_score,imdb_rating,box_office
0,0,The Batman,PG-13,2022-03-04,175,0.0,0.0,0.0
1,1,A Day to Die,0,1970-01-01,0,0.0,0.0,0.0
2,2,He Was Asking for It: A Noir Film,0,2022-04-30,0,0.0,0.0,0.0
3,3,Tyson's Run,PG,2022-03-11,103,0.0,0.0,0.0
4,4,X,R,2022-03-18,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
78,78,Aquaman and the Lost Kingdom,0,2022-12-16,0,0.0,0.0,0.0
79,79,Untitled Illumination Entertainment Project,0,2022-12-21,0,0.0,0.0,0.0
80,80,I Wanna Dance with Somebody,0,2022-12-23,0,0.0,0.0,0.0
81,81,A Man Called Otto,0,1970-01-01,0,0.0,0.0,0.0
82,82,Babylon,0,2023-01-06,0,0.0,0.0,0.0

In [40]:
#create movie table setup
genre = pd.DataFrame(movie[['movie_id','genre_name']]).rename(columns={'movie_id':'genre_id'})
#export to csv
genre.to_csv ('upcoming_genre.csv', header=True, index=False)

genre.head()

   genre_id            genre_name
0         0  Action, Crime, Drama
1         1                Action
2         2          Short, Crime
3         3                 Drama
4         4                Horror

In [41]:
#create movie table setup
movie_genre_juction = movie2.join(genre, how='outer')
movie_genre_juction = pd.DataFrame(movie_genre_juction[['movie_id','genre_id']])

#export to csv
genre.to_csv ('upcoming_movie_genre_juction.csv', header=True, index=False)

movie_genre_juction

    movie_id  genre_id
0          0         0
1          1         1
2          2         2
3          3         3
4          4         4
..       ...       ...
78        78        78
79        79        79
80        80        80
81        81        81
82        82        82

[83 rows x 2 columns]