In [1]:
import pandas as pd
import datetime as dt
from decimal import Decimal

In [6]:
load_df = pd.read_csv('output/Original_CSV_files/complete_movie_list_df_2021_2022.csv')
load_df

FileNotFoundError: [Errno 2] No such file or directory: 'output/Original_CSV_files/complete_movie_list_df_2021_2022.csv'

In [78]:
#2021-2022
converted_df.columns

Index(['Title', 'Year', 'Rated', 'Released', 'Genre', 'Director', 'Writer',
       'Actors', 'Language', 'Metascore', 'imdbRating', 'BoxOffice',
       'Runtime'],
      dtype='object')

In [79]:
#1980-2020
complete_movie_list_df5.columns

Index(['name', 'rating', 'genre', 'year', 'score', 'director', 'writer',
       'star', 'country', 'budget', 'Runtime', 'released'],
      dtype='object')

In [80]:
#joining data
frames = [complete_movie_list_df5,converted_df]

movie_df= pd.concat(frames)

In [81]:
movie_df.head(100)

,name,rating,genre,year,score,director,writer,star,country,budget,...,Rated,Released,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice
0,The Shining,R,Drama,1980.0,8.4,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
1,The Blue Lagoon,R,Adventure,1980.0,5.8,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980.0,8.7,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
3,Airplane!,PG,Comedy,1980.0,7.7,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
4,Caddyshack,R,Comedy,1980.0,7.3,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Escape from New York,R,Action,1981.0,7.2,John Carpenter,John Carpenter,Kurt Russell,United States,6000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
96,The Evil Dead,NC-17,Horror,1981.0,7.5,Sam Raimi,Sam Raimi,Bruce Campbell,United States,350000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
97,Porky's,R,Comedy,1981.0,6.2,Bob Clark,Bob Clark,Dan Monahan,Canada,2500000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
98,Blow Out,R,Crime,1981.0,7.4,Brian De Palma,Brian De Palma,John Travolta,United States,18000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
99,Clash of the Titans,PG,Action,1981.0,6.9,Desmond Davis,Beverley Cross,Laurence Olivier,United Kingdom,15000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN

In [82]:
movie_df.columns

Index(['name', 'rating', 'genre', 'year', 'score', 'director', 'writer',
       'star', 'country', 'budget', 'Runtime', 'released', 'Title', 'Year',
       'Rated', 'Released', 'Genre', 'Director', 'Writer', 'Actors',
       'Language', 'Metascore', 'imdbRating', 'BoxOffice'],
      dtype='object')

In [83]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7930 entries, 0 to 261
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        7668 non-null   object
 1   rating      7668 non-null   object
 2   genre       7668 non-null   object
 3   year        7668 non-null   float64
 4   score       7668 non-null   float64
 5   director    7668 non-null   object
 6   writer      7668 non-null   object
 7   star        7668 non-null   object
 8   country     7668 non-null   object
 9   budget      7668 non-null   float64
 10  Runtime     7930 non-null   object
 11  released    7666 non-null   object
 12  Title       262 non-null    string
 13  Year        262 non-null    float64
 14  Rated       262 non-null    string
 15  Released    257 non-null    datetime64[ns]
 16  Genre       262 non-null    string
 17  Director    262 non-null    string
 18  Writer      262 non-null    string
 19  Actors      262 non-null    string
 20  Language    262 non-null    string
 21  Metascore   262 non-null    float64
 22  imdbRating  262 non-null    float64
 23  BoxOffice   262 non-null    float64
dtypes: datetime64[ns](1), float64(7), object(9), string(7)
memory usage: 1.5+ MB

In [84]:
#checking number of null values in each column 
movie_df.isnull().sum()

name           262
rating         262
genre          262
year           262
score          262
director       262
writer         262
star           262
country        262
budget         262
Runtime          0
released       264
Title         7668
Year          7668
Rated         7668
Released      7673
Genre         7668
Director      7668
Writer        7668
Actors        7668
Language      7668
Metascore     7668
imdbRating    7668
BoxOffice     7668
dtype: int64

In [64]:
#Taking some more extra features from kaggel dataset which are not present in OMDB dataset
complete_movie_list_df5=complete_movie_list_df5[['name', 'genre', 'star', 'budget']]
complete_movie_list_df5=complete_movie_list_df5.rename(columns={'name':'Title'})

In [85]:
complete_movie_list_df5.columns

Index(['name', 'rating', 'genre', 'year', 'score', 'director', 'writer',
       'star', 'country', 'budget', 'Runtime', 'released'],
      dtype='object')

In [87]:
#merging OMDB dataset with extra features
movie_df=movie_df.merge(complete_movie_list_df5, on='Title' ,how='inner')
movie_df.shape

KeyError: 'Title'