In [1]:
import pandas as pd
import datetime as dt
from decimal import Decimal

In [32]:
load_df = pd.read_csv('output/Original_CSV_files/complete_movie_list_df_2021_2022.csv')
load_df = load_df.drop(['Unnamed: 0','Unnamed: 0.1','Production'], axis=1)
load_df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice
0,Spider-Man: No Way Home,2021,PG-13,17 Dec 2021,148 min,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,"$720,891,602"
1,Shang-Chi and the Legend of the Ten Rings,2021,PG-13,03 Sep 2021,132 min,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,"$224,543,292"
2,Venom: Let There Be Carnage,2021,PG-13,01 Oct 2021,97 min,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,"$213,550,366"
3,Black Widow,2021,PG-13,09 Jul 2021,134 min,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,"$183,651,655"
4,F9: The Fast Saga,2021,PG-13,25 Jun 2021,143 min,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,"$173,005,945"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,The Beatles: Get Back - The Rooftop Concert,2022,PG-13,30 Jan 2022,65 min,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,"$793,669"
258,The Tiger Rising,2022,PG,03 Feb 2022,102 min,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0
259,Bone Clean,2022,0,0,0,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0
260,Sparks - The Ken Sparks Story,2022,0,07 Jan 2022,88 min,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0
261,Found Wandering Lost,2022,0,25 Jan 2022,99 min,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0

In [33]:
load_df = load_df.fillna(0)
load_df

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice
0,Spider-Man: No Way Home,2021,PG-13,17 Dec 2021,148 min,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,"$720,891,602"
1,Shang-Chi and the Legend of the Ten Rings,2021,PG-13,03 Sep 2021,132 min,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,"$224,543,292"
2,Venom: Let There Be Carnage,2021,PG-13,01 Oct 2021,97 min,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,"$213,550,366"
3,Black Widow,2021,PG-13,09 Jul 2021,134 min,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,"$183,651,655"
4,F9: The Fast Saga,2021,PG-13,25 Jun 2021,143 min,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,"$173,005,945"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,The Beatles: Get Back - The Rooftop Concert,2022,PG-13,30 Jan 2022,65 min,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,"$793,669"
258,The Tiger Rising,2022,PG,03 Feb 2022,102 min,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0
259,Bone Clean,2022,0,0,0,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0
260,Sparks - The Ken Sparks Story,2022,0,07 Jan 2022,88 min,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0
261,Found Wandering Lost,2022,0,25 Jan 2022,99 min,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0

In [34]:
load_df2=load_df['Runtime'].str.split(' ', expand=True)
load_df2

       0     1
0    148   min
1    132   min
2     97   min
3    134   min
4    143   min
..   ...   ...
257   65   min
258  102   min
259    0  None
260   88   min
261   99   min

[262 rows x 2 columns]

In [35]:
load_df2 = load_df2.rename(columns={0: "a", 1: "c"})
load_df2

       a     c
0    148   min
1    132   min
2     97   min
3    134   min
4    143   min
..   ...   ...
257   65   min
258  102   min
259    0  None
260   88   min
261   99   min

[262 rows x 2 columns]

In [36]:
# to append dataframe
load_df3 = load_df.join(load_df2)
load_df3

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice,a,c
0,Spider-Man: No Way Home,2021,PG-13,17 Dec 2021,148 min,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,"$720,891,602",148,min
1,Shang-Chi and the Legend of the Ten Rings,2021,PG-13,03 Sep 2021,132 min,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,"$224,543,292",132,min
2,Venom: Let There Be Carnage,2021,PG-13,01 Oct 2021,97 min,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,"$213,550,366",97,min
3,Black Widow,2021,PG-13,09 Jul 2021,134 min,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,"$183,651,655",134,min
4,F9: The Fast Saga,2021,PG-13,25 Jun 2021,143 min,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,"$173,005,945",143,min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,The Beatles: Get Back - The Rooftop Concert,2022,PG-13,30 Jan 2022,65 min,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,"$793,669",65,min
258,The Tiger Rising,2022,PG,03 Feb 2022,102 min,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0,102,min
259,Bone Clean,2022,0,0,0,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0,0,None
260,Sparks - The Ken Sparks Story,2022,0,07 Jan 2022,88 min,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0,88,min
261,Found Wandering Lost,2022,0,25 Jan 2022,99 min,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0,99,min

In [38]:
load_df4=load_df3.drop(['c', 'Runtime'], axis=1)
load_df4

,Title,Year,Rated,Released,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice,a
0,Spider-Man: No Way Home,2021,PG-13,17 Dec 2021,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,"$720,891,602",148
1,Shang-Chi and the Legend of the Ten Rings,2021,PG-13,03 Sep 2021,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,"$224,543,292",132
2,Venom: Let There Be Carnage,2021,PG-13,01 Oct 2021,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,"$213,550,366",97
3,Black Widow,2021,PG-13,09 Jul 2021,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,"$183,651,655",134
4,F9: The Fast Saga,2021,PG-13,25 Jun 2021,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,"$173,005,945",143
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,The Beatles: Get Back - The Rooftop Concert,2022,PG-13,30 Jan 2022,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,"$793,669",65
258,The Tiger Rising,2022,PG,03 Feb 2022,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0,102
259,Bone Clean,2022,0,0,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0,0
260,Sparks - The Ken Sparks Story,2022,0,07 Jan 2022,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0,88
261,Found Wandering Lost,2022,0,25 Jan 2022,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0,99

In [40]:
load_df5 = load_df4.rename(columns={'a':'Runtime'})
load_df5

,Title,Year,Rated,Released,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice,Runtime
0,Spider-Man: No Way Home,2021,PG-13,17 Dec 2021,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,"$720,891,602",148
1,Shang-Chi and the Legend of the Ten Rings,2021,PG-13,03 Sep 2021,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,"$224,543,292",132
2,Venom: Let There Be Carnage,2021,PG-13,01 Oct 2021,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,"$213,550,366",97
3,Black Widow,2021,PG-13,09 Jul 2021,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,"$183,651,655",134
4,F9: The Fast Saga,2021,PG-13,25 Jun 2021,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,"$173,005,945",143
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,The Beatles: Get Back - The Rooftop Concert,2022,PG-13,30 Jan 2022,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,"$793,669",65
258,The Tiger Rising,2022,PG,03 Feb 2022,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0,102
259,Bone Clean,2022,0,0,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0,0
260,Sparks - The Ken Sparks Story,2022,0,07 Jan 2022,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0,88
261,Found Wandering Lost,2022,0,25 Jan 2022,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0,99

In [41]:
#converting to proper types
load_df5['Released'] = pd.to_datetime(load_df['Released'], errors='coerce')
load_df5.Title = load_df.Title.astype('string')
load_df5.Rated = load_df.Rated.astype('string')
load_df5.Runtime = load_df.Runtime.astype('string')
#load_df['Runtime'] = load_df['Runtime'].str.split(' ', 1, expand=True)
load_df5.Genre = load_df.Genre.astype('string')
load_df5.Director = load_df.Director.astype('string')
load_df5.Writer = load_df.Writer.astype('string')
load_df5.Actors = load_df.Actors.astype('string')
load_df5.Director = load_df.Director.astype('string')
load_df5.Language = load_df.Language.astype('string')
load_df5['BoxOffice'] = load_df['BoxOffice'].replace('[\$,]', '', regex=True).astype(int)
load_df5.dtypes

Title                 string
Year                   int64
Rated                 string
Released      datetime64[ns]
Genre                 string
Director              string
Writer                string
Actors                string
Language              string
Metascore            float64
imdbRating           float64
BoxOffice              int64
Runtime               string
dtype: object

In [42]:
converted_df = load_df5
converted_df

,Title,Year,Rated,Released,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice,Runtime
0,Spider-Man: No Way Home,2021,PG-13,2021-12-17,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,720891602,148 min
1,Shang-Chi and the Legend of the Ten Rings,2021,PG-13,2021-09-03,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,224543292,132 min
2,Venom: Let There Be Carnage,2021,PG-13,2021-10-01,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,213550366,97 min
3,Black Widow,2021,PG-13,2021-07-09,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,183651655,134 min
4,F9: The Fast Saga,2021,PG-13,2021-06-25,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,173005945,143 min
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,The Beatles: Get Back - The Rooftop Concert,2022,PG-13,2022-01-30,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,793669,65 min
258,The Tiger Rising,2022,PG,2022-02-03,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0,102 min
259,Bone Clean,2022,0,NaT,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0,0
260,Sparks - The Ken Sparks Story,2022,0,2022-01-07,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0,88 min
261,Found Wandering Lost,2022,0,2022-01-25,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0,99 min

In [43]:
#export to csv
converted_df.to_csv ('output/Original_CSV_files/clean_movie_list_df_2021_2022.csv', header=True, index=False)
converted_df

,Title,Year,Rated,Released,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice,Runtime
0,Spider-Man: No Way Home,2021,PG-13,2021-12-17,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,720891602,148 min
1,Shang-Chi and the Legend of the Ten Rings,2021,PG-13,2021-09-03,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,224543292,132 min
2,Venom: Let There Be Carnage,2021,PG-13,2021-10-01,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,213550366,97 min
3,Black Widow,2021,PG-13,2021-07-09,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,183651655,134 min
4,F9: The Fast Saga,2021,PG-13,2021-06-25,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,173005945,143 min
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,The Beatles: Get Back - The Rooftop Concert,2022,PG-13,2022-01-30,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,793669,65 min
258,The Tiger Rising,2022,PG,2022-02-03,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0,102 min
259,Bone Clean,2022,0,NaT,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0,0
260,Sparks - The Ken Sparks Story,2022,0,2022-01-07,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0,88 min
261,Found Wandering Lost,2022,0,2022-01-25,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0,99 min

In [44]:
movie_list2 = pd.read_csv('output/Original_CSV_files/movies.csv')
movie_list2

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
7664,Dream Round,NaN,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,NaN,NaN,Cactus Blue Entertainment,90.0
7665,Saving Mbango,NaN,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,NaN,Embi Productions,NaN
7666,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
7667,Tee em el,NaN,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,NaN,NaN,PK 65 Films,102.0

In [45]:
#clean dataframe
#movie_list2 = pd.DataFrame(movie_list2.rename(columns={'name':'title','rating':'movie_rating','genre':'genre_name','year':'year','released':'release_date',
#'score':'imdb_rating','votes':'votes', 'director':'Director', 'writer':'Writer', 'star':'Actors', 'country':'country', 'budget':'BoxOffice', 'gross':'gross',
#'company':'company','runtime':'runtime',}))

#clean dataframe
#converted_df = pd.DataFrame(converted_df.rename(columns={'Title':'title','Rated':'movie_rating','Released':'release_date',
#'Runtime':'runtime', 'Genre': 'genre_name', 'Metascore':'metascore','imdbRating':'imdb_rating'}))

#movie_list2

In [46]:
movie_list2 = movie_list2.fillna(0)
movie_list2

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,0.0,0,90.0
7664,Dream Round,0,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,0.0,0.0,Cactus Blue Entertainment,90.0
7665,Saving Mbango,0,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,0.0,Embi Productions,0.0
7666,It's Just Us,0,Drama,2020,"October 1, 2020 (United States)",0.0,0.0,James Randall,James Randall,Christina Roz,United States,15000.0,0.0,0,120.0
7667,Tee em el,0,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,0.0,0.0,PK 65 Films,102.0

In [47]:
release_date=movie_list2['released'].str.split('(', expand=True)
release_date

                      0               1
0        June 13, 1980   United States)
1         July 2, 1980   United States)
2        June 20, 1980   United States)
3         July 2, 1980   United States)
4        July 25, 1980   United States)
...                 ...             ...
7663  October 23, 2020   United States)
7664  February 7, 2020   United States)
7665    April 27, 2020        Cameroon)
7666   October 1, 2020   United States)
7667   August 19, 2020   United States)

[7668 rows x 2 columns]

In [48]:
release_date2 = release_date.rename(columns={0: "a", 1: "c"})
release_date2

                      a               c
0        June 13, 1980   United States)
1         July 2, 1980   United States)
2        June 20, 1980   United States)
3         July 2, 1980   United States)
4        July 25, 1980   United States)
...                 ...             ...
7663  October 23, 2020   United States)
7664  February 7, 2020   United States)
7665    April 27, 2020        Cameroon)
7666   October 1, 2020   United States)
7667   August 19, 2020   United States)

[7668 rows x 2 columns]

In [49]:
# to append dataframe
complete_movie_list_df = movie_list2.join(release_date2)
complete_movie_list_df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,a,c
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,"June 13, 1980",United States)
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,"July 2, 1980",United States)
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,"June 20, 1980",United States)
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,"July 2, 1980",United States)
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,"July 25, 1980",United States)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,0.0,0,90.0,"October 23, 2020",United States)
7664,Dream Round,0,Comedy,2020,"February 7, 2020 (United States)",4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,0.0,0.0,Cactus Blue Entertainment,90.0,"February 7, 2020",United States)
7665,Saving Mbango,0,Drama,2020,"April 27, 2020 (Cameroon)",5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,0.0,Embi Productions,0.0,"April 27, 2020",Cameroon)
7666,It's Just Us,0,Drama,2020,"October 1, 2020 (United States)",0.0,0.0,James Randall,James Randall,Christina Roz,United States,15000.0,0.0,0,120.0,"October 1, 2020",United States)
7667,Tee em el,0,Horror,2020,"August 19, 2020 (United States)",5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,0.0,0.0,PK 65 Films,102.0,"August 19, 2020",United States)

In [50]:
complete_movie_list_df2=complete_movie_list_df.drop(['c', 'released'], axis=1)
complete_movie_list_df2

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime,a
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,"June 13, 1980"
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,"July 2, 1980"
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,"June 20, 1980"
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,"July 2, 1980"
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,"July 25, 1980"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,2020,3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,0.0,0,90.0,"October 23, 2020"
7664,Dream Round,0,Comedy,2020,4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,0.0,0.0,Cactus Blue Entertainment,90.0,"February 7, 2020"
7665,Saving Mbango,0,Drama,2020,5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,0.0,Embi Productions,0.0,"April 27, 2020"
7666,It's Just Us,0,Drama,2020,0.0,0.0,James Randall,James Randall,Christina Roz,United States,15000.0,0.0,0,120.0,"October 1, 2020"
7667,Tee em el,0,Horror,2020,5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,0.0,0.0,PK 65 Films,102.0,"August 19, 2020"

In [51]:
complete_movie_list_df3 = complete_movie_list_df2.rename(columns={'a':'released','runtime':'Runtime'})
complete_movie_list_df3

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,Runtime,released
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,46998772.0,Warner Bros.,146.0,"June 13, 1980"
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,58853106.0,Columbia Pictures,104.0,"July 2, 1980"
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,538375067.0,Lucasfilm,124.0,"June 20, 1980"
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,83453539.0,Paramount Pictures,88.0,"July 2, 1980"
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,39846344.0,Orion Pictures,98.0,"July 25, 1980"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,2020,3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,0.0,0,90.0,"October 23, 2020"
7664,Dream Round,0,Comedy,2020,4.7,36.0,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,0.0,0.0,Cactus Blue Entertainment,90.0,"February 7, 2020"
7665,Saving Mbango,0,Drama,2020,5.7,29.0,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,0.0,Embi Productions,0.0,"April 27, 2020"
7666,It's Just Us,0,Drama,2020,0.0,0.0,James Randall,James Randall,Christina Roz,United States,15000.0,0.0,0,120.0,"October 1, 2020"
7667,Tee em el,0,Horror,2020,5.7,7.0,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,0.0,0.0,PK 65 Films,102.0,"August 19, 2020"

In [52]:
#converting to proper types
complete_movie_list_df3['released'] = pd.to_datetime(complete_movie_list_df3['released'], errors='coerce')
complete_movie_list_df3.name = complete_movie_list_df3.name.astype('string')
complete_movie_list_df3.rating = complete_movie_list_df3.rating.astype('string')
complete_movie_list_df3.Runtime = complete_movie_list_df3.Runtime.astype('string')
#load_df['Runtime'] = load_df['Runtime'].str.split(' ', 1, expand=True)
complete_movie_list_df3.genre = complete_movie_list_df3.genre.astype('string')
complete_movie_list_df3.writer = complete_movie_list_df3.writer.astype('string')
complete_movie_list_df3.star = complete_movie_list_df3.star.astype('string')
complete_movie_list_df3.director = complete_movie_list_df3.director.astype('string')
#complete_movie_list_df3['budget'] = complete_movie_list_df3['budget'].replace('[\$,]', '', regex=True).astype(int)
complete_movie_list_df3.dtypes

name                string
rating              string
genre               string
year                 int64
score              float64
votes              float64
director            string
writer              string
star                string
country             object
budget             float64
gross              float64
company             object
Runtime             string
released    datetime64[ns]
dtype: object

In [53]:
complete_movie_list_df4 = complete_movie_list_df3.drop(['votes','gross','company'], axis=1)
complete_movie_list_df4

,name,rating,genre,year,score,director,writer,star,country,budget,Runtime,released
0,The Shining,R,Drama,1980,8.4,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,146.0,1980-06-13
1,The Blue Lagoon,R,Adventure,1980,5.8,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,104.0,1980-07-02
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,124.0,1980-06-20
3,Airplane!,PG,Comedy,1980,7.7,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,88.0,1980-07-02
4,Caddyshack,R,Comedy,1980,7.3,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,98.0,1980-07-25
...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,2020,3.1,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,90.0,2020-10-23
7664,Dream Round,0,Comedy,2020,4.7,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,0.0,90.0,2020-02-07
7665,Saving Mbango,0,Drama,2020,5.7,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,0.0,2020-04-27
7666,It's Just Us,0,Drama,2020,0.0,James Randall,James Randall,Christina Roz,United States,15000.0,120.0,2020-10-01
7667,Tee em el,0,Horror,2020,5.7,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,0.0,102.0,2020-08-19

In [54]:
#export to csv
complete_movie_list_df4.to_csv ('output/Original_CSV_files/clean_movie_list.csv', header=True, index=False)
complete_movie_list_df4

,name,rating,genre,year,score,director,writer,star,country,budget,Runtime,released
0,The Shining,R,Drama,1980,8.4,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,146.0,1980-06-13
1,The Blue Lagoon,R,Adventure,1980,5.8,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,104.0,1980-07-02
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,124.0,1980-06-20
3,Airplane!,PG,Comedy,1980,7.7,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,88.0,1980-07-02
4,Caddyshack,R,Comedy,1980,7.3,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,98.0,1980-07-25
...,...,...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,2020,3.1,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,90.0,2020-10-23
7664,Dream Round,0,Comedy,2020,4.7,Dusty Dukatz,Lisa Huston,Michael Saquella,United States,0.0,90.0,2020-02-07
7665,Saving Mbango,0,Drama,2020,5.7,Nkanya Nkwai,Lynno Lovert,Onyama Laura,United States,58750.0,0.0,2020-04-27
7666,It's Just Us,0,Drama,2020,0.0,James Randall,James Randall,Christina Roz,United States,15000.0,120.0,2020-10-01
7667,Tee em el,0,Horror,2020,5.7,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,South Africa,0.0,102.0,2020-08-19

In [2]:
complete_movie_list_df5 = pd.read_csv('Archieve/clean_movie_list.csv')
complete_movie_list_df5

FileNotFoundError: [Errno 2] No such file or directory: 'Archieve/clean_movie_list.csv'

In [78]:
#2021-2022
converted_df.columns

Index(['Title', 'Year', 'Rated', 'Released', 'Genre', 'Director', 'Writer',
       'Actors', 'Language', 'Metascore', 'imdbRating', 'BoxOffice',
       'Runtime'],
      dtype='object')

In [79]:
#1980-2020
complete_movie_list_df5.columns

Index(['name', 'rating', 'genre', 'year', 'score', 'director', 'writer',
       'star', 'country', 'budget', 'Runtime', 'released'],
      dtype='object')

In [80]:
#joining data
frames = [complete_movie_list_df5,converted_df]

movie_df= pd.concat(frames)

In [81]:
movie_df.head(100)

,name,rating,genre,year,score,director,writer,star,country,budget,...,Rated,Released,Genre,Director,Writer,Actors,Language,Metascore,imdbRating,BoxOffice
0,The Shining,R,Drama,1980.0,8.4,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
1,The Blue Lagoon,R,Adventure,1980.0,5.8,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980.0,8.7,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
3,Airplane!,PG,Comedy,1980.0,7.7,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
4,Caddyshack,R,Comedy,1980.0,7.3,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Escape from New York,R,Action,1981.0,7.2,John Carpenter,John Carpenter,Kurt Russell,United States,6000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
96,The Evil Dead,NC-17,Horror,1981.0,7.5,Sam Raimi,Sam Raimi,Bruce Campbell,United States,350000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
97,Porky's,R,Comedy,1981.0,6.2,Bob Clark,Bob Clark,Dan Monahan,Canada,2500000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
98,Blow Out,R,Crime,1981.0,7.4,Brian De Palma,Brian De Palma,John Travolta,United States,18000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN
99,Clash of the Titans,PG,Action,1981.0,6.9,Desmond Davis,Beverley Cross,Laurence Olivier,United Kingdom,15000000.0,...,<NA>,NaT,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN

In [82]:
movie_df.columns

Index(['name', 'rating', 'genre', 'year', 'score', 'director', 'writer',
       'star', 'country', 'budget', 'Runtime', 'released', 'Title', 'Year',
       'Rated', 'Released', 'Genre', 'Director', 'Writer', 'Actors',
       'Language', 'Metascore', 'imdbRating', 'BoxOffice'],
      dtype='object')

In [83]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7930 entries, 0 to 261
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        7668 non-null   object
 1   rating      7668 non-null   object
 2   genre       7668 non-null   object
 3   year        7668 non-null   float64
 4   score       7668 non-null   float64
 5   director    7668 non-null   object
 6   writer      7668 non-null   object
 7   star        7668 non-null   object
 8   country     7668 non-null   object
 9   budget      7668 non-null   float64
 10  Runtime     7930 non-null   object
 11  released    7666 non-null   object
 12  Title       262 non-null    string
 13  Year        262 non-null    float64
 14  Rated       262 non-null    string
 15  Released    257 non-null    datetime64[ns]
 16  Genre       262 non-null    string
 17  Director    262 non-null    string
 18  Writer      262 non-null    string
 19  Actors      262 non-null    string
 20  Language    262 non-null    string
 21  Metascore   262 non-null    float64
 22  imdbRating  262 non-null    float64
 23  BoxOffice   262 non-null    float64
dtypes: datetime64[ns](1), float64(7), object(9), string(7)
memory usage: 1.5+ MB

In [84]:
#checking number of null values in each column 
movie_df.isnull().sum()

name           262
rating         262
genre          262
year           262
score          262
director       262
writer         262
star           262
country        262
budget         262
Runtime          0
released       264
Title         7668
Year          7668
Rated         7668
Released      7673
Genre         7668
Director      7668
Writer        7668
Actors        7668
Language      7668
Metascore     7668
imdbRating    7668
BoxOffice     7668
dtype: int64

In [64]:
#Taking some more extra features from kaggel dataset which are not present in OMDB dataset
complete_movie_list_df5=complete_movie_list_df5[['name', 'genre', 'star', 'budget']]
complete_movie_list_df5=complete_movie_list_df5.rename(columns={'name':'Title'})

In [85]:
complete_movie_list_df5.columns

Index(['name', 'rating', 'genre', 'year', 'score', 'director', 'writer',
       'star', 'country', 'budget', 'Runtime', 'released'],
      dtype='object')

In [87]:
#merging OMDB dataset with extra features
movie_df=movie_df.merge(complete_movie_list_df5, on='Title' ,how='inner')
movie_df.shape

KeyError: 'Title'