In [8]:
import pandas as pd
import datetime as dt
from decimal import Decimal

In [9]:
movie_list2 = pd.read_csv('output/clean_movie_list_df2.csv')
movie_list2

,name,rating,genre,score,director,writer,star,budget,Run,released
0,The Shining,R,Drama,8.4,Stanley Kubrick,Stephen King,Jack Nicholson,19000000.0,146.0,1980-06-13
1,The Blue Lagoon,R,Adventure,5.8,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,4500000.0,104.0,1980-07-02
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,8.7,Irvin Kershner,Leigh Brackett,Mark Hamill,18000000.0,124.0,1980-06-20
3,Airplane!,PG,Comedy,7.7,Jim Abrahams,Jim Abrahams,Robert Hays,3500000.0,88.0,1980-07-02
4,Caddyshack,R,Comedy,7.3,Harold Ramis,Brian Doyle-Murray,Chevy Chase,6000000.0,98.0,1980-07-25
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,3.1,Joseph Ebanks,Joseph Ebanks,Shannon Bond,7000.0,90.0,2020-10-23
7664,Dream Round,0,Comedy,4.7,Dusty Dukatz,Lisa Huston,Michael Saquella,0.0,90.0,2020-02-07
7665,Saving Mbango,0,Drama,5.7,Nkanya Nkwai,Lynno Lovert,Onyama Laura,58750.0,0.0,2020-04-27
7666,It's Just Us,0,Drama,0.0,James Randall,James Randall,Christina Roz,15000.0,120.0,2020-10-01
7667,Tee em el,0,Horror,5.7,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,0.0,102.0,2020-08-19

In [10]:
#clean dataframe
movie_list2 = pd.DataFrame(movie_list2.rename(columns={'name':'title','rating':'movie_rating','genre': 'genre_name', 'score':'imdb_rating',
                                                      'star':'actors', 'budget':'box_office', 'Run': 'run_time', 'released':'release_date'}))
movie_list2

,title,movie_rating,genre_name,imdb_rating,director,writer,actors,box_office,run_time,release_date
0,The Shining,R,Drama,8.4,Stanley Kubrick,Stephen King,Jack Nicholson,19000000.0,146.0,1980-06-13
1,The Blue Lagoon,R,Adventure,5.8,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,4500000.0,104.0,1980-07-02
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,8.7,Irvin Kershner,Leigh Brackett,Mark Hamill,18000000.0,124.0,1980-06-20
3,Airplane!,PG,Comedy,7.7,Jim Abrahams,Jim Abrahams,Robert Hays,3500000.0,88.0,1980-07-02
4,Caddyshack,R,Comedy,7.3,Harold Ramis,Brian Doyle-Murray,Chevy Chase,6000000.0,98.0,1980-07-25
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,Drama,3.1,Joseph Ebanks,Joseph Ebanks,Shannon Bond,7000.0,90.0,2020-10-23
7664,Dream Round,0,Comedy,4.7,Dusty Dukatz,Lisa Huston,Michael Saquella,0.0,90.0,2020-02-07
7665,Saving Mbango,0,Drama,5.7,Nkanya Nkwai,Lynno Lovert,Onyama Laura,58750.0,0.0,2020-04-27
7666,It's Just Us,0,Drama,0.0,James Randall,James Randall,Christina Roz,15000.0,120.0,2020-10-01
7667,Tee em el,0,Horror,5.7,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,0.0,102.0,2020-08-19

In [13]:
movie_list2 = movie_list2[["title", "movie_rating", "release_date", "genre_name", 'director','writer','actors','imdb_rating','box_office','run_time']]
movie_list2

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [14]:
#export to csv
movie_list2.to_csv ('output/clean_movie_list_df_completed.csv', header=True, index=False)
movie_list2

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [15]:
movie_list3 = pd.read_csv('output/clean_movie_list_df_2122.csv')
movie_list3

,movie_id,title,movie_rating,release_date,genre_name,Director,Writer,Actors,Language,metascore,imdb_rating,BoxOffice,runtime
0,0,Spider-Man: No Way Home,PG-13,2021-12-17,"Action, Adventure, Fantasy",Jon Watts,"Chris McKenna, Erik Sommers, Stan Lee","Tom Holland, Zendaya, Benedict Cumberbatch",English,71.0,8.7,720891602,148
1,1,Shang-Chi and the Legend of the Ten Rings,PG-13,2021-09-03,"Action, Adventure, Fantasy",Destin Daniel Cretton,"Dave Callaham, Destin Daniel Cretton, Andrew L...","Simu Liu, Awkwafina, Tony Chiu-Wai Leung","English, Mandarin",71.0,7.5,224543292,132
2,2,Venom: Let There Be Carnage,PG-13,2021-10-01,"Action, Adventure, Sci-Fi",Andy Serkis,"Kelly Marcel, Tom Hardy","Tom Hardy, Woody Harrelson, Michelle Williams",English,49.0,6.0,213550366,97
3,3,Black Widow,PG-13,2021-07-09,"Action, Adventure, Sci-Fi",Cate Shortland,"Eric Pearson, Jac Schaeffer, Ned Benson","Scarlett Johansson, Florence Pugh, David Harbour","English, Russian, Norwegian, Hungarian, Macedo...",67.0,6.7,183651655,134
4,4,F9: The Fast Saga,PG-13,2021-06-25,"Action, Crime, Thriller",Justin Lin,"Daniel Casey, Justin Lin, Alfredo Botello","Vin Diesel, Michelle Rodriguez, Jordana Brewster",English,58.0,5.2,173005945,143
...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,257,The Beatles: Get Back - The Rooftop Concert,PG-13,2022-01-30,Music,Peter Jackson,0,"The Beatles, George Harrison, John Lennon",English,0.0,0.0,793669,65
258,258,The Tiger Rising,PG,2022-02-03,Family,Ray Giarratana,"Kate DiCamillo, Ray Giarratana","Dennis Quaid, Katharine McPhee, Queen Latifah",English,33.0,5.8,0,102
259,259,Bone Clean,0,NaN,"Short, Drama",Katy Maudlin,Morgan Rose,"Keegan Joyce, Gemma Bird Matheson",English,0.0,0.0,0,0
260,260,Sparks - The Ken Sparks Story,0,2022-01-07,Biography,Jeff Joslin,Ciera Danielle,"Chad Sparks, Chanda Childress, Jeff Joslin",English,0.0,0.0,0,88
261,261,Found Wandering Lost,0,2022-01-25,"Drama, Thriller",Nicholaus James,"Nicholaus James, James Thomas","Eric Bowles, Dylan Brown, Jessi Burkette",0,0.0,5.8,0,99

In [16]:
#clean dataframe
movie_list3 = pd.DataFrame(movie_list2.rename(columns={'Director':'director', 'Writer':'writer', 'Actors':'actors',
                                                       'BoxOffice':'box_office', 'runtime': 'run_time'}))
movie_list3

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [19]:
#export to csv
movie_list3.to_csv ('output/clean_movie_list_df_2122_completed.csv', header=True, index=False)
movie_list3

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [20]:
movie_list4 = pd.read_csv('output/clean_movie_list_df_completed.csv')
movie_list4

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [21]:
#export to csv
movie_list5 = pd.read_csv('output/clean_movie_list_df_2122_completed.csv')
movie_list5

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [23]:
# to append dataframe
completed_movie_list_df = movie_list4.append(movie_list5)
completed_movie_list_df

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [24]:
#export final csv
completed_movie_list_df.to_csv ('output/completed_movie_list_df.csv', header=True, index=False)
completed_movie_list_df

,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0
...,...,...,...,...,...,...,...,...,...,...
7663,More to Life,0,2020-10-23,Drama,Joseph Ebanks,Joseph Ebanks,Shannon Bond,3.1,7000.0,90.0
7664,Dream Round,0,2020-02-07,Comedy,Dusty Dukatz,Lisa Huston,Michael Saquella,4.7,0.0,90.0
7665,Saving Mbango,0,2020-04-27,Drama,Nkanya Nkwai,Lynno Lovert,Onyama Laura,5.7,58750.0,0.0
7666,It's Just Us,0,2020-10-01,Drama,James Randall,James Randall,Christina Roz,0.0,15000.0,120.0
7667,Tee em el,0,2020-08-19,Horror,Pereko Mosia,Pereko Mosia,Siyabonga Mabaso,5.7,0.0,102.0

In [33]:
completed_movie_list_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15336 entries, 0 to 7667
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         15336 non-null  object
 1   movie_rating  15336 non-null  object
 2   release_date  15332 non-null  object
 3   genre_name    15336 non-null  object
 4   director      15336 non-null  object
 5   writer        15336 non-null  object
 6   actors        15336 non-null  object
 7   imdb_rating   15336 non-null  float64
 8   box_office    15336 non-null  float64
 9   run_time      15336 non-null  float64
dtypes: float64(3), object(7)
memory usage: 1.3+ MB

In [35]:
import pandas as pd
import numpy as np
import psycopg2
import sqlalchemy 
from sqlalchemy import create_engine

from config import username, password

In [36]:
from sqlalchemy import create_engine
engine = create_engine(f'postgresql://{username}:{password}@localhost:5432/movies_db')
connection = engine.connect()

In [39]:
completed_movie_list_df.to_sql(name='movie_list', con=engine, if_exists='append', index=True)

In [40]:
pd.read_sql_query('select * from movie_list', con=engine).head()

,index,title,movie_rating,release_date,genre_name,director,writer,actors,imdb_rating,box_office,run_time
0,0,The Shining,R,1980-06-13,Drama,Stanley Kubrick,Stephen King,Jack Nicholson,8.4,19000000.0,146.0
1,1,The Blue Lagoon,R,1980-07-02,Adventure,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,5.8,4500000.0,104.0
2,2,Star Wars: Episode V - The Empire Strikes Back,PG,1980-06-20,Action,Irvin Kershner,Leigh Brackett,Mark Hamill,8.7,18000000.0,124.0
3,3,Airplane!,PG,1980-07-02,Comedy,Jim Abrahams,Jim Abrahams,Robert Hays,7.7,3500000.0,88.0
4,4,Caddyshack,R,1980-07-25,Comedy,Harold Ramis,Brian Doyle-Murray,Chevy Chase,7.3,6000000.0,98.0