In [1]:
# Dependencies
import requests
from bs4 import BeautifulSoup as bs
import requests
import numpy as np
import time
import pandas as pd
import csv
import json

In [2]:
#Beautiful Soup 
url = 'https://www.imdb.com/calendar/?ref_=nv_mv_cal'
response = requests.get(url)
soup = bs(response.text, 'html.parser')

In [3]:
lis = soup.body.find_all('li')

In [4]:
movies =[]
for li in lis:
                # If td element has an anchor...
    if (li.a):
                    # And the anchor has non-blank text...
        if (li.a.text):
                        # Append the td to the list
            movies.append(li)

In [5]:
len(movies)

360

In [6]:
titles =[]
for x in range(360):
    print(movies[x].text)
    titles.append(movies[x].text)

The Batman (2022)


A Day to Die (2022)


Great Freedom (2021)


Asking for It (2021)


Tyson's Run (2022)


Offseason (2021)


X (2022)


Operation Fortune: Ruse de guerre (2022)


Jujutsu Kaisen 0: The Movie (2021)


The Outfit (2022)


Cheaper by the Dozen (2022)


Alice (2022)


The Unbreakable Boy (2022)


Umma (2022)


Where Is Anne Frank (2021)


Man of God (2021)


The Lost City (2022)


The Duke (2020)


Everything Everywhere All at Once (2022)


Mothering Sunday (2021)


Nitram (2021)


Morbius (2022)


The Contractor (2022)


You Won't Be Alone (2022)


Barbarians (2021)


Iris Warriors (2022)


Sonic the Hedgehog 2 (2022)


Ambulance (2022)


Cow (2021)


Aline (2020)


Father Stu (2022)


Fantastic Beasts: The Secrets of Dumbledore (2022)


Paris, 13th District (2021)


The Bad Guys (2022)


The Northman (2022)


The Unbearable Weight of Massive Talent (2022)


Petite Maman (2021)


Hatching (2022)


Vortex (2021)


Firebird (2021)


Memory (2022)


Doctor Strange in the Multiverse of Madness (2022)


Happening (2021)


The Twin (2022)


Firestarter (2022)


The Innocents (2021)


Downton Abbey: A New Era (2022)


Men (2022)


DC League of Super-Pets (2022)


Top Gun: Maverick (2022)


The Bob's Burgers Movie (2022)


Terror on the Prairie (2022)


Jurassic World Dominion (2022)


Lightyear (2022)


Elvis (2022)


The Black Phone (2021)


Shotgun Wedding (2022)


Minions 2: The Rise of Gru (2022)


Thor: Love and Thunder (2022)


Bullet Train (2022)


Mrs Harris Goes to Paris (2022)


The Wrong Place (2022)


Nope (2022)


Where the Crawdads Sing (2022)


Blazing Samurai (2022)


Black Adam (2022)


Guns 3: Alias Billy the Kid (2022)


Secret Headquarters (2022)


The Man from Toronto (2022)


Samaritan (2022)


After Ever Happy (2022)


Salem's Lot (2022)


Dark Harvest (2022)


The Woman King (2022)


Don't Worry Darling (2022)


Puss in Boots: The Last Wish (2022)


Spider-Man: Across the Spider-Verse - Part One (2022)


Till (2022)


Halloween Ends (2022)


Ticket to Paradise (2022)


The Devil's Light (2022)


The Monkey King: The Legend Begins (2022)


The Flash (2022)


Untitled David O. Russell (2022)


Black Panther: Wakanda Forever (2022)


Spellbound (2022)


Thirteen Lives (2022)


Creed III (2022)


The Fabelmans (2022)


Strange World (2022)


Avatar 2 (2022)


Aquaman and the Lost Kingdom (2022)


Untitled Illumination Entertainment Project (2022)


I Wanna Dance with Somebody (2022)


A Man Called Otto (2022)


Babylon (2022)


The Amazing Maurice (2023)


Kraven the Hunter (2023)


Knock at the Cabin (2023)


The Marvels (2023)


Afghanistan


Albania


Algeria


American Samoa


Andorra


Angola


Anguilla


Antarctica


Antigua & Barbuda


Argentina


Armenia


Aruba


Australia


Austria


Azerbaijan


Bahamas


Bahrain


Bangladesh


Barbados


Belarus


Belgium


Belize


Benin


Bermuda


Bhutan


Bolivia


Bosnia & Herzegovina


Botswana


Bouvet Island


Brazil


British Indian Ocean Territory


British Virgin Islands


Brunei


Bulgaria


Burkina Faso


Burundi


Cambodia


Cameroon


Canada


Cape Verde


Caribbean Netherlands


Cayman Islands


Central African Republic


Chad


Chile


China


Christmas Island


Cocos (Keeling) Islands


Colombia


Comoros


Congo - Brazzaville


Congo - Kinshasa


Cook Islands


Costa Rica


Croatia


Cuba


Curaçao


Cyprus


Czechia


Côte d’Ivoire


Denmark


Djibouti


Dominica


Dominican Republic


Ecuador


Egypt


El Salvador


Equatorial Guinea


Eritrea


Estonia


Eswatini


Ethiopia


Falkland Islands


Faroe Islands


Fiji


Finland


France


French Guiana


French Polynesia


French Southern Territories


Gabon


Gambia


Georgia


Germany


Ghana


Gibraltar


Greece


Greenland


Grenada


Guadeloupe


Guam


Guatemala


Guernsey


Guinea


Guinea-Bissau


Guyana


Haiti


Heard & McDonald Islands


Honduras


Hong Kong SAR China


Hungary


Iceland


India


Indonesia


Iran


Iraq


Ireland


Isle of Man


Israel


Italy


Jamaica


Japan


Jersey


Jordan


Kazakhstan


Kenya


Kiribati


Kuwait


Kyrgyzstan


Laos


Latvia


Lebanon


Lesotho


Liberia


Libya


Liechtenstein


Lithuania


Luxembourg


Macao SAR China


Madagascar


Malawi


Malaysia


Maldives


Mali


Malta


Marshall Islands


Martinique


Mauritania


Mauritius


Mayotte


Mexico


Micronesia


Moldova


Monaco


Mongolia


Montenegro


Montserrat


Morocco


Mozambique


Myanmar (Burma)


Namibia


Nauru


Nepal


Netherlands


New Caledonia


New Zealand


Nicaragua


Niger


Nigeria


Niue


Norfolk Island


North Korea


North Macedonia


Northern Mariana Islands


Norway


Oman


Pakistan


Palau


Palestinian Territories


Panama


Papua New Guinea


Paraguay


Peru


Philippines


Pitcairn Islands


Poland


Portugal


Puerto Rico


Qatar


Romania


Russia


Rwanda


Réunion


Samoa


San Marino


Saudi Arabia


Senegal


Serbia


Seychelles


Sierra Leone


Singapore


Slovakia


Slovenia


Solomon Islands


Somalia


South Africa


South Georgia & South Sandwich Islands


South Korea


Spain


Sri Lanka


St. Barthélemy


St. Helena


St. Kitts & Nevis


St. Lucia


St. Martin


St. Pierre & Miquelon


St. Vincent & Grenadines


Sudan


Suriname


Svalbard & Jan Mayen


Sweden


Switzerland


Syria


São Tomé & Príncipe


Taiwan


Tajikistan


Tanzania


Thailand


Timor-Leste


Togo


Tokelau


Tonga


Trinidad & Tobago


Tunisia


Turkey


Turkmenistan


Turks & Caicos Islands


Tuvalu


U.S. Outlying Islands


U.S. Virgin Islands


Uganda


Ukraine


United Arab Emirates


United Kingdom


United States


Uruguay


Uzbekistan


Vanuatu


Vatican City


Venezuela


Vietnam


Wallis & Futuna


Western Sahara


Yemen


Zambia


Zimbabwe


Åland Islands

Get the IMDb App
View Full Site
Help
Site Index
IMDbPro
Box Office Mojo
IMDb Developer
Press Room
Advertising
Jobs
Conditions of Use
Privacy Policy
Interest-Based Ads

In [7]:
print(titles)

['\nThe Batman (2022)\n                        ', '\nA Day to Die (2022)\n                        ', '\nGreat Freedom (2021)\n                        ', '\nAsking for It (2021)\n                        ', "\nTyson's Run (2022)\n                        ", '\nOffseason (2021)\n                        ', '\nX (2022)\n                        ', '\nOperation Fortune: Ruse de guerre (2022)\n                        ', '\nJujutsu Kaisen 0: The Movie (2021)\n                        ', '\nThe Outfit (2022)\n                        ', '\nCheaper by the Dozen (2022)\n                        ', '\nAlice (2022)\n                        ', '\nThe Unbreakable Boy (2022)\n                        ', '\nUmma (2022)\n                        ', '\nWhere Is Anne Frank (2021)\n                        ', '\nMan of God (2021)\n                        ', '\nThe Lost City (2022)\n                        ', '\nThe Duke (2020)\n                        ', '\nEverything Everywhere All at Once (2022)\n                        ', '\nMothering Sunday (2021)\n                        ', '\nNitram (2021)\n                        ', '\nMorbius (2022)\n                        ', '\nThe Contractor (2022)\n                        ', "\nYou Won't Be Alone (2022)\n                        ", '\nBarbarians (2021)\n                        ', '\nIris Warriors (2022)\n                        ', '\nSonic the Hedgehog 2 (2022)\n                        ', '\nAmbulance (2022)\n                        ', '\nCow (2021)\n                        ', '\nAline (2020)\n                        ', '\nFather Stu (2022)\n                        ', '\nFantastic Beasts: The Secrets of Dumbledore (2022)\n                        ', '\nParis, 13th District (2021)\n                        ', '\nThe Bad Guys (2022)\n                        ', '\nThe Northman (2022)\n                        ', '\nThe Unbearable Weight of Massive Talent (2022)\n                        ', '\nPetite Maman (2021)\n                        ', '\nHatching (2022)\n                        ', '\nVortex (2021)\n                        ', '\nFirebird (2021)\n                        ', '\nMemory (2022)\n                        ', '\nDoctor Strange in the Multiverse of Madness (2022)\n                        ', '\nHappening (2021)\n                        ', '\nThe Twin (2022)\n                        ', '\nFirestarter (2022)\n                        ', '\nThe Innocents (2021)\n                        ', '\nDownton Abbey: A New Era (2022)\n                        ', '\nMen (2022)\n                        ', '\nDC League of Super-Pets (2022)\n                        ', '\nTop Gun: Maverick (2022)\n                        ', "\nThe Bob's Burgers Movie (2022)\n                        ", '\nTerror on the Prairie (2022)\n                        ', '\nJurassic World Dominion (2022)\n                        ', '\nLightyear (2022)\n                        ', '\nElvis (2022)\n                        ', '\nThe Black Phone (2021)\n                        ', '\nShotgun Wedding (2022)\n                        ', '\nMinions 2: The Rise of Gru (2022)\n                        ', '\nThor: Love and Thunder (2022)\n                        ', '\nBullet Train (2022)\n                        ', '\nMrs Harris Goes to Paris (2022)\n                        ', '\nThe Wrong Place (2022)\n                        ', '\nNope (2022)\n                        ', '\nWhere the Crawdads Sing (2022)\n                        ', '\nBlazing Samurai (2022)\n                        ', '\nBlack Adam (2022)\n                        ', '\nGuns 3: Alias Billy the Kid (2022)\n                        ', '\nSecret Headquarters (2022)\n                        ', '\nThe Man from Toronto (2022)\n                        ', '\nSamaritan (2022)\n                        ', '\nAfter Ever Happy (2022)\n                        ', "\nSalem's Lot (2022)\n                        ", '\nDark Harvest (2022)\n                        ', '\nThe Woman King (2022)\n                        ', "\nDon't Worry Darling (2022)\n                        ", '\nPuss in Boots: The Last Wish (2022)\n                        ', '\nSpider-Man: Across the Spider-Verse - Part One (2022)\n                        ', '\nTill (2022)\n                        ', '\nHalloween Ends (2022)\n                        ', '\nTicket to Paradise (2022)\n                        ', "\nThe Devil's Light (2022)\n                        ", '\nThe Monkey King: The Legend Begins (2022)\n                        ', '\nThe Flash (2022)\n                        ', '\nUntitled David O. Russell (2022)\n                        ', '\nBlack Panther: Wakanda Forever (2022)\n                        ', '\nSpellbound (2022)\n                        ', '\nThirteen Lives (2022)\n                        ', '\nCreed III (2022)\n                        ', '\nThe Fabelmans (2022)\n                        ', '\nStrange World (2022)\n                        ', '\nAvatar 2 (2022)\n                        ', '\nAquaman and the Lost Kingdom (2022)\n                        ', '\nUntitled Illumination Entertainment Project (2022)\n                        ', '\nI Wanna Dance with Somebody (2022)\n                        ', '\nA Man Called Otto (2022)\n                        ', '\nBabylon (2022)\n                        ', '\nThe Amazing Maurice (2023)\n                        ', '\nKraven the Hunter (2023)\n                        ', '\nKnock at the Cabin (2023)\n                        ', '\nThe Marvels (2023)\n                        ', '\nAfghanistan\n', '\nAlbania\n', '\nAlgeria\n', '\nAmerican Samoa\n', '\nAndorra\n', '\nAngola\n', '\nAnguilla\n', '\nAntarctica\n', '\nAntigua & Barbuda\n', '\nArgentina\n', '\nArmenia\n', '\nAruba\n', '\nAustralia\n', '\nAustria\n', '\nAzerbaijan\n', '\nBahamas\n', '\nBahrain\n', '\nBangladesh\n', '\nBarbados\n', '\nBelarus\n', '\nBelgium\n', '\nBelize\n', '\nBenin\n', '\nBermuda\n', '\nBhutan\n', '\nBolivia\n', '\nBosnia & Herzegovina\n', '\nBotswana\n', '\nBouvet Island\n', '\nBrazil\n', '\nBritish Indian Ocean Territory\n', '\nBritish Virgin Islands\n', '\nBrunei\n', '\nBulgaria\n', '\nBurkina Faso\n', '\nBurundi\n', '\nCambodia\n', '\nCameroon\n', '\nCanada\n', '\nCape Verde\n', '\nCaribbean Netherlands\n', '\nCayman Islands\n', '\nCentral African Republic\n', '\nChad\n', '\nChile\n', '\nChina\n', '\nChristmas Island\n', '\nCocos (Keeling) Islands\n', '\nColombia\n', '\nComoros\n', '\nCongo - Brazzaville\n', '\nCongo - Kinshasa\n', '\nCook Islands\n', '\nCosta Rica\n', '\nCroatia\n', '\nCuba\n', '\nCuraçao\n', '\nCyprus\n', '\nCzechia\n', '\nCôte d’Ivoire\n', '\nDenmark\n', '\nDjibouti\n', '\nDominica\n', '\nDominican Republic\n', '\nEcuador\n', '\nEgypt\n', '\nEl Salvador\n', '\nEquatorial Guinea\n', '\nEritrea\n', '\nEstonia\n', '\nEswatini\n', '\nEthiopia\n', '\nFalkland Islands\n', '\nFaroe Islands\n', '\nFiji\n', '\nFinland\n', '\nFrance\n', '\nFrench Guiana\n', '\nFrench Polynesia\n', '\nFrench Southern Territories\n', '\nGabon\n', '\nGambia\n', '\nGeorgia\n', '\nGermany\n', '\nGhana\n', '\nGibraltar\n', '\nGreece\n', '\nGreenland\n', '\nGrenada\n', '\nGuadeloupe\n', '\nGuam\n', '\nGuatemala\n', '\nGuernsey\n', '\nGuinea\n', '\nGuinea-Bissau\n', '\nGuyana\n', '\nHaiti\n', '\nHeard & McDonald Islands\n', '\nHonduras\n', '\nHong Kong SAR China\n', '\nHungary\n', '\nIceland\n', '\nIndia\n', '\nIndonesia\n', '\nIran\n', '\nIraq\n', '\nIreland\n', '\nIsle of Man\n', '\nIsrael\n', '\nItaly\n', '\nJamaica\n', '\nJapan\n', '\nJersey\n', '\nJordan\n', '\nKazakhstan\n', '\nKenya\n', '\nKiribati\n', '\nKuwait\n', '\nKyrgyzstan\n', '\nLaos\n', '\nLatvia\n', '\nLebanon\n', '\nLesotho\n', '\nLiberia\n', '\nLibya\n', '\nLiechtenstein\n', '\nLithuania\n', '\nLuxembourg\n', '\nMacao SAR China\n', '\nMadagascar\n', '\nMalawi\n', '\nMalaysia\n', '\nMaldives\n', '\nMali\n', '\nMalta\n', '\nMarshall Islands\n', '\nMartinique\n', '\nMauritania\n', '\nMauritius\n', '\nMayotte\n', '\nMexico\n', '\nMicronesia\n', '\nMoldova\n', '\nMonaco\n', '\nMongolia\n', '\nMontenegro\n', '\nMontserrat\n', '\nMorocco\n', '\nMozambique\n', '\nMyanmar (Burma)\n', '\nNamibia\n', '\nNauru\n', '\nNepal\n', '\nNetherlands\n', '\nNew Caledonia\n', '\nNew Zealand\n', '\nNicaragua\n', '\nNiger\n', '\nNigeria\n', '\nNiue\n', '\nNorfolk Island\n', '\nNorth Korea\n', '\nNorth Macedonia\n', '\nNorthern Mariana Islands\n', '\nNorway\n', '\nOman\n', '\nPakistan\n', '\nPalau\n', '\nPalestinian Territories\n', '\nPanama\n', '\nPapua New Guinea\n', '\nParaguay\n', '\nPeru\n', '\nPhilippines\n', '\nPitcairn Islands\n', '\nPoland\n', '\nPortugal\n', '\nPuerto Rico\n', '\nQatar\n', '\nRomania\n', '\nRussia\n', '\nRwanda\n', '\nRéunion\n', '\nSamoa\n', '\nSan Marino\n', '\nSaudi Arabia\n', '\nSenegal\n', '\nSerbia\n', '\nSeychelles\n', '\nSierra Leone\n', '\nSingapore\n', '\nSlovakia\n', '\nSlovenia\n', '\nSolomon Islands\n', '\nSomalia\n', '\nSouth Africa\n', '\nSouth Georgia & South Sandwich Islands\n', '\nSouth Korea\n', '\nSpain\n', '\nSri Lanka\n', '\nSt. Barthélemy\n', '\nSt. Helena\n', '\nSt. Kitts & Nevis\n', '\nSt. Lucia\n', '\nSt. Martin\n', '\nSt. Pierre & Miquelon\n', '\nSt. Vincent & Grenadines\n', '\nSudan\n', '\nSuriname\n', '\nSvalbard & Jan Mayen\n', '\nSweden\n', '\nSwitzerland\n', '\nSyria\n', '\nSão Tomé & Príncipe\n', '\nTaiwan\n', '\nTajikistan\n', '\nTanzania\n', '\nThailand\n', '\nTimor-Leste\n', '\nTogo\n', '\nTokelau\n', '\nTonga\n', '\nTrinidad & Tobago\n', '\nTunisia\n', '\nTurkey\n', '\nTurkmenistan\n', '\nTurks & Caicos Islands\n', '\nTuvalu\n', '\nU.S. Outlying Islands\n', '\nU.S. Virgin Islands\n', '\nUganda\n', '\nUkraine\n', '\nUnited Arab Emirates\n', '\nUnited Kingdom\n', '\nUnited States\n', '\nUruguay\n', '\nUzbekistan\n', '\nVanuatu\n', '\nVatican City\n', '\nVenezuela\n', '\nVietnam\n', '\nWallis & Futuna\n', '\nWestern Sahara\n', '\nYemen\n', '\nZambia\n', '\nZimbabwe\n', '\nÅland Islands\n', 'Get the IMDb App', 'View Full Site', 'Help', 'Site Index', 'IMDbPro', 'Box Office Mojo', 'IMDb Developer', 'Press Room', 'Advertising', 'Jobs', 'Conditions of Use', 'Privacy Policy', 'Interest-Based Ads']

In [8]:
test=pd.DataFrame(titles,columns=["test"])
test

                                                 test
0       \nThe Batman (2022)\n
1     \nA Day to Die (2022)\n
2    \nGreat Freedom (2021)\n
3    \nAsking for It (2021)\n
4      \nTyson's Run (2022)\n
..                                                ...
355                                       Advertising
356                                              Jobs
357                                 Conditions of Use
358                                    Privacy Policy
359                                Interest-Based Ads

[360 rows x 1 columns]

In [9]:
test[["test","trash"]]=test["test"].str.split("\n",1,expand=True)
#test[["trash","trash2"]]=test["trash"].str.split("\n",1,expand=True)
test

                   test                                           trash
0                           The Batman (2022)\n
1                         A Day to Die (2022)\n
2                        Great Freedom (2021)\n
3                        Asking for It (2021)\n
4                          Tyson's Run (2022)\n
..                  ...                                             ...
355         Advertising                                            None
356                Jobs                                            None
357   Conditions of Use                                            None
358      Privacy Policy                                            None
359  Interest-Based Ads                                            None

[360 rows x 2 columns]

In [10]:
test_2 = pd.DataFrame(test["trash"])
test_2[["trash","trash2"]]=test["trash"].str.split("\n",1,expand=True)
test_2

                    trash                    trash2
0       The Batman (2022)
1     A Day to Die (2022)
2    Great Freedom (2021)
3    Asking for It (2021)
4      Tyson's Run (2022)
..                    ...                       ...
355                  None                      None
356                  None                      None
357                  None                      None
358                  None                      None
359                  None                      None

[360 rows x 2 columns]

In [11]:
upcoming_list = pd.DataFrame(test_2["trash"])
upcoming_list = upcoming_list.iloc[:100,:]
upcoming_list[["trash","trash2"]]=upcoming_list["trash"].str.split("(",1,expand=True)
upcoming_list = pd.DataFrame(upcoming_list["trash"])
upcoming_list.to_csv('output/upcoming.csv',header=True)
upcoming_list

                   trash
0            The Batman
1          A Day to Die
2         Great Freedom
3         Asking for It
4           Tyson's Run
..                   ...
95              Babylon
96  The Amazing Maurice
97    Kraven the Hunter
98   Knock at the Cabin
99          The Marvels

[100 rows x 1 columns]

In [12]:
clean_upcoming = pd.read_csv('output/upcoming.csv')
clean_upcoming = clean_upcoming["trash"].values.tolist()
clean_upcoming

['The Batman ',
 'A Day to Die ',
 'Great Freedom ',
 'Asking for It ',
 "Tyson's Run ",
 'Offseason ',
 'X ',
 'Operation Fortune: Ruse de guerre ',
 'Jujutsu Kaisen 0: The Movie ',
 'The Outfit ',
 'Cheaper by the Dozen ',
 'Alice ',
 'The Unbreakable Boy ',
 'Umma ',
 'Where Is Anne Frank ',
 'Man of God ',
 'The Lost City ',
 'The Duke ',
 'Everything Everywhere All at Once ',
 'Mothering Sunday ',
 'Nitram ',
 'Morbius ',
 'The Contractor ',
 "You Won't Be Alone ",
 'Barbarians ',
 'Iris Warriors ',
 'Sonic the Hedgehog 2 ',
 'Ambulance ',
 'Cow ',
 'Aline ',
 'Father Stu ',
 'Fantastic Beasts: The Secrets of Dumbledore ',
 'Paris, 13th District ',
 'The Bad Guys ',
 'The Northman ',
 'The Unbearable Weight of Massive Talent ',
 'Petite Maman ',
 'Hatching ',
 'Vortex ',
 'Firebird ',
 'Memory ',
 'Doctor Strange in the Multiverse of Madness ',
 'Happening ',
 'The Twin ',
 'Firestarter ',
 'The Innocents ',
 'Downton Abbey: A New Era ',
 'Men ',
 'DC League of Super-Pets ',
 'Top Gun: Maverick ',
 "The Bob's Burgers Movie ",
 'Terror on the Prairie ',
 'Jurassic World Dominion ',
 'Lightyear ',
 'Elvis ',
 'The Black Phone ',
 'Shotgun Wedding ',
 'Minions 2: The Rise of Gru ',
 'Thor: Love and Thunder ',
 'Bullet Train ',
 'Mrs Harris Goes to Paris ',
 'The Wrong Place ',
 'Nope ',
 'Where the Crawdads Sing ',
 'Blazing Samurai ',
 'Black Adam ',
 'Guns 3: Alias Billy the Kid ',
 'Secret Headquarters ',
 'The Man from Toronto ',
 'Samaritan ',
 'After Ever Happy ',
 "Salem's Lot ",
 'Dark Harvest ',
 'The Woman King ',
 "Don't Worry Darling ",
 'Puss in Boots: The Last Wish ',
 'Spider-Man: Across the Spider-Verse - Part One ',
 'Till ',
 'Halloween Ends ',
 'Ticket to Paradise ',
 "The Devil's Light ",
 'The Monkey King: The Legend Begins ',
 'The Flash ',
 'Untitled David O. Russell ',
 'Black Panther: Wakanda Forever ',
 'Spellbound ',
 'Thirteen Lives ',
 'Creed III ',
 'The Fabelmans ',
 'Strange World ',
 'Avatar 2 ',
 'Aquaman and the Lost Kingdom ',
 'Untitled Illumination Entertainment Project ',
 'I Wanna Dance with Somebody ',
 'A Man Called Otto ',
 'Babylon ',
 'The Amazing Maurice ',
 'Kraven the Hunter ',
 'Knock at the Cabin ',
 'The Marvels ']

In [13]:
#API call section 
url = "http://www.omdbapi.com/?apikey=" + "66144c46" + "&t=" 
#my key: 3a389bae
#michaelas: 66144c46
responses = {'Title': [], 'Year': [], 'Rated': [], 'Released': [], 'Runtime': [], 'Genre': [], 'Director': [], 'Writer': [], 'Actors': [], 
'Plot': [], 'Language': [], 'Poster': [], 'Metascore': [], 'imdbRating': [], 'BoxOffice': [], 'Production': []}

i = 1
j = 1
for movie in clean_upcoming:
    movie_data = requests.get(url + movie + '&y=2022').json()
    #responses.append(movie_data)
    try:
        responses['Title'].append(movie_data['Title'])
        responses['Year'].append(movie_data['Year'])
        responses['Rated'].append(movie_data['Rated'])
        responses['Released'].append(movie_data['Released'])
        responses['Runtime'].append(movie_data['Runtime'])
        responses['Genre'].append(movie_data['Genre'])
        responses['Director'].append(movie_data['Director'])
        responses['Writer'].append(movie_data['Writer'])
        responses['Actors'].append(movie_data['Actors'])
        responses['Plot'].append(movie_data['Plot'])
        responses['Language'].append(movie_data['Language'])
        responses['Poster'].append(movie_data['Poster'])
        responses['Metascore'].append(movie_data['Metascore'])
        responses['imdbRating'].append(movie_data['imdbRating'])
        responses['BoxOffice'].append(movie_data['BoxOffice'])
        responses['Production'].append(movie_data['Production'])
        print('Good Data')

    except:
        print("Bad Data")
    pass    

    #delay for every 100 calls    
    if i == 900:
        time.sleep(65)
        i = 0

#track number of call
        j += 1
    i += 1
    
else:
    print('----\nData Retrieval Complete\n----')

Good Data
Good Data
Bad Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Good Data
Good Data
Good Data
Bad Data
Bad Data
Good Data
Good Data
Good Data
Bad Data
Bad Data
Good Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Bad Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Good Data
Bad Data
Bad Data
Bad Data
Bad Data
----
Data Retrieval Complete
----

In [14]:
#create dataframe from dictionary
upcoming_2022 = pd.DataFrame.from_dict(responses, orient='index')
upcoming_2022= upcoming_2022.transpose()

#export to csv
upcoming_2022.to_csv ('output/upcoming2022.csv', header=True)

#display preview
upcoming_2022

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,Language,Poster,Metascore,imdbRating,BoxOffice,Production
0,The Batman,2022,PG-13,04 Mar 2022,175 min,"Action, Crime, Drama",Matt Reeves,"Matt Reeves, Peter Craig, Bob Kane","Zoë Kravitz, Robert Pattinson, Barry Keoghan","When the Riddler, a sadistic serial killer, be...",English,https://m.media-amazon.com/images/M/MV5BYTExZT...,N/A,N/A,N/A,N/A
1,A Day to Die,2022,N/A,N/A,N/A,Action,Wes Miller,"Rab Berry, Scott Mallace","Bruce Willis, Frank Grillo, Kevin Dillon",After killing a drug syndicate member while pr...,English,https://m.media-amazon.com/images/M/MV5BM2Q1ZD...,N/A,N/A,N/A,N/A
2,He Was Asking for It: A Noir Film,2022,N/A,30 Apr 2022,N/A,"Short, Crime",Rocky Karlage,"Rocky Karlage, Staci Layne Wilson","Rocky Karlage, Patrick Lamba, Charlie Jiin",The meek fight back against a sleazy film prod...,English,https://m.media-amazon.com/images/M/MV5BMjA5NG...,N/A,N/A,N/A,N/A
3,Tyson's Run,2022,PG,11 Mar 2022,103 min,Drama,Kim Bass,Kim Bass,"Major Dodson, Amy Smart, Barkhad Abdi",An unathletic boy with autism strives to becom...,English,https://m.media-amazon.com/images/M/MV5BODQ3NG...,N/A,N/A,N/A,N/A
4,X,2022,R,18 Mar 2022,N/A,Horror,Ti West,Ti West,"Jenna Ortega, Mia Goth, Brittany Snow","In 1979, a group of young filmmakers set out t...",English,https://m.media-amazon.com/images/M/MV5BYjI1OW...,N/A,N/A,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,Aquaman and the Lost Kingdom,2022,N/A,16 Dec 2022,N/A,"Action, Adventure, Fantasy",James Wan,"David Leslie Johnson-McGoldrick, Paul Norris, ...","Temuera Morrison, Nicole Kidman, Jason Momoa",Plot unknown. Sequel to the 2018 film 'Aquaman.',English,https://m.media-amazon.com/images/M/MV5BM2QyYT...,N/A,N/A,N/A,N/A
79,Untitled Illumination Entertainment Project,2022,N/A,21 Dec 2022,N/A,"Animation, Adventure, Comedy","Aaron Horvath, Michael Jelenic","Matthew Fogel, Shigeru Miyamoto","Anya Taylor-Joy, Chris Pratt, Seth Rogen",A plumber named Mario travels through an under...,English,https://m.media-amazon.com/images/M/MV5BODMzNm...,N/A,N/A,N/A,N/A
80,I Wanna Dance with Somebody,2022,N/A,23 Dec 2022,N/A,"Biography, Music",Kasi Lemmons,Anthony McCarten,"Stanley Tucci, Tamara Tunie, Clarke Peters","The joyous, emotional and heart-breaking celeb...",N/A,N/A,N/A,N/A,N/A,N/A
81,A Man Called Otto,2022,N/A,N/A,N/A,"Comedy, Drama",Marc Forster,Fredrik Backman,"Tom Hanks, Rachel Keller, Manuel Garcia-Rulfo",A cranky retired man strikes up an unlikely fr...,English,N/A,N/A,N/A,N/A,N/A
82,Babylon,2022,N/A,06 Jan 2023,N/A,Drama,Damien Chazelle,Damien Chazelle,"Brad Pitt, Margot Robbie, Olivia Wilde",Plot unknown. Rumored to be set in period Holl...,English,https://m.media-amazon.com/images/M/MV5BOGI5N2...,N/A,N/A,N/A,N/A